### ISSUE TITLE
Not sure how to test a zsh completion

### ISSUE THREAD

**Issue by joshka** [Homebrew/homebrew-completions#134]
There seems to be only tests for bash completions in this repo. I've spent a while reading the zshcompsys pages, but can't seem to find a way to programmatically trigger completion in zsh like `complete -p` in bash. Can anyone point me in the right direction?

**Comment by joshka** [comment]
The following did the trick:
```shell
zsh -c 'fpath+=/usr/local/share/zsh/site-functions; autoload -U compinit && compinit; whence _brew_cask'
```
Where `_brew_cask` is the completion function I'm testing.

**Comment by bfontaine** [comment]
Great! There weren’t any zsh test because nobody spent time like you did digging in the docs to find how to programmatically trigger zsh completion.

**Comment by joshka** [comment]
Credit where credit is due. @apjanke suggested something pretty close to this to me.
