### ISSUE TITLE
docker-completion & docker are in conflict

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-completions#155]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:
`docker` and `docker-completion` have file in conflict. 

Same issue had beed reported in homebrew-completions https://github.com/Homebrew/homebrew-completions/issues/155

```brew reinstall docker-completion 
==> Reinstalling homebrew/completions/docker-completion
Error: Could not symlink etc/bash_completion.d/docker
Target /usr/local/etc/bash_completion.d/docker
is a symlink belonging to docker. You can unlink it:
  brew unlink docker

To force the link and overwrite all conflicting files:
  brew link --overwrite docker-completion

To list all files that would be deleted:
  brew link --overwrite --dry-run docker-completion
```

**Comment by bfontaine** [comment]
[This is already documented](https://github.com/Homebrew/homebrew-completions/blob/9fcfacaa2c002db713fe2667d032b5b8421df351/docker-completion.rb#L10-L11):

```
$ brew info docker-completion
homebrew/completions/docker-completion: stable 1.12.2, HEAD
Bash, Zsh and Fish completion for Docker
https://github.com/docker/docker
Conflicts with: docker                 <--- here
Not installed
From: https://github.com/Homebrew/homebrew-completions/blob/master/docker-completion.rb
```

It should have warned you on install:

```
$ brew install docker-completion
==> Installing docker-completion from homebrew/completions
Error: Cannot install homebrew/completions/docker-completion because conflicting formulae are installed.

  docker: because docker already includes these completion scripts

Please `brew unlink docker` before continuing.

Unlinking removes a formula's symlinks from /home/baptiste/.linuxbrew. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```

**Comment by yurikoles** [comment]
What is the purpose of installing completions without docker installed?

**Comment by bfontaine** [comment]
Some people prefer to install `docker` outside of Homebrew. See e.g. [this comment](https://github.com/Homebrew/homebrew-completions/pull/110#r52820812).
